---
driver_plugin: vagrant
driver_config:
#  require_chef_omnibus: latest
  customize:
    memory: 512

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-12.04
    driver_config:
      # https://github.com/chef/bento
      box: opscode-ubuntu-12.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    run_list:
      - recipe[apt]
      - recipe[curl]

  - name: ubuntu-14.04
    driver_config:
      # https://github.com/chef/bento
      box: opscode-ubuntu-14.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
    run_list:
      - recipe[apt]
      - recipe[curl]

suites:
  - name: default
    run_list:
      - recipe[afterdark-webhead::default]

  - name: ssl
    run_list:
      - recipe[test_nginx_certs] # This is just forcing it to be included
      - recipe[afterdark-webhead::ssl]
    attributes:
      afterdark-webhead:
        ssl:
          cert_cookbook: test_nginx_certs
          cert: certs/test_nginx.cert.pem
          key: certs/test_nginx.key.pem
